# Generated by Django 4.0.4 on 2022-06-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='discription',
        ),
    ]
